"""会员储值：balance + balance_txn

Revision ID: 0481b7dea684
Revises: 5050caa9e222
Create Date: 2026-09-16 16:33:42.380200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0481b7dea684'
down_revision = '5050caa9e222'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('member',
    sa.Column('openid', sa.String(length=64), nullable=True),
    sa.Column('unionid', sa.String(length=64), nullable=True),
    sa.Column('mobile', sa.String(length=20), nullable=True),
    sa.Column('nickname', sa.String(length=32), nullable=False),
    sa.Column('avatar', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('member', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_member_mobile'), ['mobile'], unique=True)
        batch_op.create_index(batch_op.f('ix_member_openid'), ['openid'], unique=True)
        batch_op.create_index(batch_op.f('ix_member_unionid'), ['unionid'], unique=False)

    op.create_table('balance',
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('principal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('bonus', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['member.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('balance', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_balance_member_id'), ['member_id'], unique=True)

    op.create_table('balance_txn',
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('principal_delta', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('bonus_delta', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('principal_after', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('bonus_after', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('legacy_no', sa.String(length=64), nullable=False),
    sa.Column('remark', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['member.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('balance_txn', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_balance_txn_member_id'), ['member_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_balance_txn_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_balance_txn_type'), ['type'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('balance_txn', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_balance_txn_type'))
        batch_op.drop_index(batch_op.f('ix_balance_txn_order_id'))
        batch_op.drop_index(batch_op.f('ix_balance_txn_member_id'))

    op.drop_table('balance_txn')
    with op.batch_alter_table('balance', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_balance_member_id'))

    op.drop_table('balance')
    with op.batch_alter_table('member', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_member_unionid'))
        batch_op.drop_index(batch_op.f('ix_member_openid'))
        batch_op.drop_index(batch_op.f('ix_member_mobile'))

    op.drop_table('member')
    # ### end Alembic commands ###
