"""add store table

Revision ID: 06582cacde3c
Revises: efa05728af52
Create Date: 2026-09-11 19:30:02.101902

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '06582cacde3c'
down_revision = 'efa05728af52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('store',
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('store_type', sa.String(length=20), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('business_status', sa.String(length=20), nullable=False),
    sa.Column('run_mode', sa.String(length=20), nullable=False),
    sa.Column('remark', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    with op.batch_alter_table('store', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_store_name'), ['name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('store', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_store_name'))

    op.drop_table('store')
    # ### end Alembic commands ###
