"""积分：points + points_txn

Revision ID: 2d651d48f58d
Revises: 52bd067fde97
Create Date: 2026-09-16 18:48:51.309459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d651d48f58d'
down_revision = '52bd067fde97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('points',
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('balance', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['member.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('points', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_points_member_id'), ['member_id'], unique=True)

    op.create_table('points_txn',
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('delta', sa.Integer(), nullable=False),
    sa.Column('after', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('legacy_no', sa.String(length=64), nullable=False),
    sa.Column('remark', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['member.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('points_txn', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_points_txn_member_id'), ['member_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_points_txn_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_points_txn_type'), ['type'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('points_txn', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_points_txn_type'))
        batch_op.drop_index(batch_op.f('ix_points_txn_order_id'))
        batch_op.drop_index(batch_op.f('ix_points_txn_member_id'))

    op.drop_table('points_txn')
    with op.batch_alter_table('points', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_points_member_id'))

    op.drop_table('points')
    # ### end Alembic commands ###
