"""门店加展示字段（简介、营业时间），给顾客端首页用

Revision ID: 321704076614
Revises: dcf63283acb5
Create Date: 2026-09-17 22:59:27.925250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '321704076614'
down_revision = 'dcf63283acb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('store', schema=None) as batch_op:
        # store 表里已经有门店了，加必填列得给 server_default——不然 Alembic
        # 不知道老行填什么，ALTER 直接失败（README「新模块的固定流程」里记着，
        # 这已经是第 5 次了）。空字符串就是这两个字段该有的默认值
        batch_op.add_column(sa.Column('description', sa.String(length=255),
                                      nullable=False, server_default=''))
        batch_op.add_column(sa.Column('business_hours', sa.String(length=64),
                                      nullable=False, server_default=''))
        batch_op.alter_column('description', server_default=None)
        batch_op.alter_column('business_hours', server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('store', schema=None) as batch_op:
        batch_op.drop_column('business_hours')
        batch_op.drop_column('description')

    # ### end Alembic commands ###
