"""add refund tables

Revision ID: 4ae2743e0109
Revises: d1c2d668b8ee
Create Date: 2026-09-12 17:04:59.008257

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '4ae2743e0109'
down_revision = 'd1c2d668b8ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refund',
    sa.Column('refund_no', sa.String(length=40), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('applicant_id', sa.Integer(), nullable=True),
    sa.Column('applicant_name', sa.String(length=50), nullable=False),
    sa.Column('approver_id', sa.Integer(), nullable=True),
    sa.Column('approver_name', sa.String(length=50), nullable=False),
    sa.Column('approve_remark', sa.String(length=255), nullable=False),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['applicant_id'], ['staff.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['approver_id'], ['staff.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('refund', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_refund_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_refund_refund_no'), ['refund_no'], unique=True)
        batch_op.create_index(batch_op.f('ix_refund_status'), ['status'], unique=False)

    op.create_table('refund_txn',
    sa.Column('refund_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('method', sa.String(length=20), nullable=False),
    sa.Column('transaction_no', sa.String(length=64), nullable=False),
    sa.Column('operator_id', sa.Integer(), nullable=True),
    sa.Column('operator_name', sa.String(length=50), nullable=False),
    sa.Column('settled_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['operator_id'], ['staff.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['refund_id'], ['refund.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('refund_txn', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_refund_txn_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_refund_txn_refund_id'), ['refund_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_refund_txn_transaction_no'), ['transaction_no'], unique=False)

    with op.batch_alter_table('order', schema=None) as batch_op:
        # 给已有数据的表加 NOT NULL 列必须先给 server_default，否则已有的订单行
        # 填不进去（MySQL 严格模式下直接报错）。填完再把默认值摘掉，
        # 让库里的结构和模型定义保持一致——模型用的是 Python 侧 default
        batch_op.add_column(sa.Column('refunded_amount', sa.Numeric(precision=10, scale=2),
                                      nullable=False, server_default='0'))
        batch_op.alter_column('refunded_amount', server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('refunded_amount')

    with op.batch_alter_table('refund_txn', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refund_txn_transaction_no'))
        batch_op.drop_index(batch_op.f('ix_refund_txn_refund_id'))
        batch_op.drop_index(batch_op.f('ix_refund_txn_order_id'))

    op.drop_table('refund_txn')
    with op.batch_alter_table('refund', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refund_status'))
        batch_op.drop_index(batch_op.f('ix_refund_refund_no'))
        batch_op.drop_index(batch_op.f('ix_refund_order_id'))

    op.drop_table('refund')
    # ### end Alembic commands ###
