"""order_item_option 加 quantity（加料可以加多份）

Revision ID: 5050caa9e222
Revises: 90526ea3b9db
Create Date: 2026-09-16 11:27:05.679617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5050caa9e222'
down_revision = '90526ea3b9db'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('order_item_option', schema=None) as batch_op:
        # 表里已经有数据了，NOT NULL 的新列必须给 server_default，否则迁移直接失败。
        # 老行都是「加了一份」——那会儿还不支持多份。
        batch_op.add_column(sa.Column('quantity', sa.Integer(), nullable=False,
                                      server_default='1'))
        # 填完老数据就把默认值撤掉：之后新行由模型上的 default=1 负责，
        # 免得数据库里留一个和模型重复的隐式默认
        batch_op.alter_column('quantity', server_default=None)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_item_option', schema=None) as batch_op:
        batch_op.drop_column('quantity')

    # ### end Alembic commands ###
