"""排班：班次模板 + 排班记录

Revision ID: 59e03d66039a
Revises: 321704076614
Create Date: 2026-09-18 10:37:24.662850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59e03d66039a'
down_revision = '321704076614'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shift_template',
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    # 外键显式起名——交给 MySQL 起就是 `shift_template_ibfk_1`（带序号），
    # 换个环境顺序一变就对不上。惯例见 README「新模块的固定流程」
    sa.ForeignKeyConstraint(['store_id'], ['store.id'],
                            name='fk_shift_template_store_id', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'name', name='uq_shift_template_store_name')
    )
    with op.batch_alter_table('shift_template', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shift_template_store_id'), ['store_id'], unique=False)

    op.create_table('shift_assignment',
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.Column('shift_id', sa.Integer(), nullable=False),
    sa.Column('work_date', sa.Date(), nullable=False),
    sa.Column('remark', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['shift_id'], ['shift_template.id'],
                            name='fk_shift_assignment_shift_id', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'],
                            name='fk_shift_assignment_staff_id', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['store_id'], ['store.id'],
                            name='fk_shift_assignment_store_id', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('staff_id', 'work_date', 'shift_id', name='uq_shift_assignment_staff_date_shift')
    )
    with op.batch_alter_table('shift_assignment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shift_assignment_shift_id'), ['shift_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_shift_assignment_staff_id'), ['staff_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_shift_assignment_store_id'), ['store_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_shift_assignment_work_date'), ['work_date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shift_assignment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shift_assignment_work_date'))
        batch_op.drop_index(batch_op.f('ix_shift_assignment_store_id'))
        batch_op.drop_index(batch_op.f('ix_shift_assignment_staff_id'))
        batch_op.drop_index(batch_op.f('ix_shift_assignment_shift_id'))

    op.drop_table('shift_assignment')
    with op.batch_alter_table('shift_template', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shift_template_store_id'))

    op.drop_table('shift_template')
    # ### end Alembic commands ###
