"""add order query token

Revision ID: 90526ea3b9db
Revises: e4286b14b783
Create Date: 2026-09-12 17:37:19.577960

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '90526ea3b9db'
down_revision = 'e4286b14b783'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        # 老订单的令牌填空串：它们是在这个字段存在之前下的单，本来就没有令牌。
        # 空串查不到任何订单（find_order 会拒掉空令牌），相当于「这批老单不能用
        # 顾客端查」——比编一个假令牌安全，也比让迁移失败好。
        # NOT NULL 的列加给已有数据的表必须先给 server_default，填完再摘掉。
        batch_op.add_column(sa.Column('query_token', sa.String(length=32),
                                      nullable=False, server_default=''))
        batch_op.alter_column('query_token', server_default=None)
        batch_op.create_index(batch_op.f('ix_order_query_token'), ['query_token'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_query_token'))
        batch_op.drop_column('query_token')

    # ### end Alembic commands ###
