"""优惠券：券模板 + 用户持券

Revision ID: 9b07332e7800
Revises: f4928cf14b52
Create Date: 2026-09-16 20:08:35.633678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b07332e7800'
down_revision = 'f4928cf14b52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coupon_template',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('min_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('valid_from', sa.DateTime(), nullable=True),
    sa.Column('valid_to', sa.DateTime(), nullable=True),
    sa.Column('total_quantity', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('coupon_template', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_coupon_template_status'), ['status'], unique=False)

    op.create_table('coupon_template_store',
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['store.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['coupon_template.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('template_id', 'store_id')
    )
    op.create_table('user_coupon',
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.Column('issued_by_id', sa.Integer(), nullable=True),
    sa.Column('issued_by_name', sa.String(length=50), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('used_order_id', sa.Integer(), nullable=True),
    sa.Column('used_store_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['issued_by_id'], ['staff.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['member_id'], ['member.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['template_id'], ['coupon_template.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['used_order_id'], ['order.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['used_store_id'], ['store.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_coupon', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_coupon_member_id'), ['member_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_coupon_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_coupon_template_id'), ['template_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_coupon_used_order_id'), ['used_order_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_coupon', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_coupon_used_order_id'))
        batch_op.drop_index(batch_op.f('ix_user_coupon_template_id'))
        batch_op.drop_index(batch_op.f('ix_user_coupon_status'))
        batch_op.drop_index(batch_op.f('ix_user_coupon_member_id'))

    op.drop_table('user_coupon')
    op.drop_table('coupon_template_store')
    with op.batch_alter_table('coupon_template', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_coupon_template_status'))

    op.drop_table('coupon_template')
    # ### end Alembic commands ###
