"""add store_dish table

Revision ID: c8677caa80e3
Revises: 9b95f5a49873
Create Date: 2026-09-12 11:53:48.312700

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'c8677caa80e3'
down_revision = '9b95f5a49873'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('store_dish',
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('dish_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('daily_limit', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dish_id'], ['dish.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['store_id'], ['store.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'dish_id', name='uq_store_dish')
    )
    with op.batch_alter_table('store_dish', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_store_dish_dish_id'), ['dish_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_store_dish_store_id'), ['store_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('store_dish', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_store_dish_store_id'))
        batch_op.drop_index(batch_op.f('ix_store_dish_dish_id'))

    op.drop_table('store_dish')
    # ### end Alembic commands ###
