"""顾客端登录：验证码表；券模板加自领开关和每人限领

Revision ID: dcf63283acb5
Revises: e4c5a3fe57a2
Create Date: 2026-09-17 21:21:52.651121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcf63283acb5'
down_revision = 'e4c5a3fe57a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('member_verify_code',
    sa.Column('mobile', sa.String(length=20), nullable=False),
    sa.Column('code', sa.String(length=6), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('member_verify_code', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_member_verify_code_mobile'), ['mobile'], unique=False)

    # coupon_template 里已经有券了，加必填列得给 server_default——
    # 不然 Alembic 不知道老行填什么，ALTER 直接失败（README「新模块的固定流程」里记着）。
    # `false` 是老券该有的值：默认都不挂到券中心，跟新字段的默认值一致
    with op.batch_alter_table('coupon_template', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_claimable', sa.Boolean(), nullable=False,
                                      server_default=sa.text('false')))
        batch_op.alter_column('is_claimable', server_default=None)
        batch_op.add_column(sa.Column('per_member_limit', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coupon_template', schema=None) as batch_op:
        batch_op.drop_column('per_member_limit')
        batch_op.drop_column('is_claimable')

    with op.batch_alter_table('member_verify_code', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_member_verify_code_mobile'))

    op.drop_table('member_verify_code')
    # ### end Alembic commands ###
