"""add groupon voucher table

Revision ID: e4286b14b783
Revises: 4ae2743e0109
Create Date: 2026-09-12 17:15:33.511019

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'e4286b14b783'
down_revision = '4ae2743e0109'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groupon_voucher',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=True),
    sa.Column('verified_by_id', sa.Integer(), nullable=True),
    sa.Column('verified_by_name', sa.String(length=50), nullable=False),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['payment_id'], ['payment.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['verified_by_id'], ['staff.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('groupon_voucher', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_groupon_voucher_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_groupon_voucher_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_groupon_voucher_payment_id'), ['payment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_groupon_voucher_platform'), ['platform'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('groupon_voucher', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_groupon_voucher_platform'))
        batch_op.drop_index(batch_op.f('ix_groupon_voucher_payment_id'))
        batch_op.drop_index(batch_op.f('ix_groupon_voucher_order_id'))
        batch_op.drop_index(batch_op.f('ix_groupon_voucher_code'))

    op.drop_table('groupon_voucher')
    # ### end Alembic commands ###
