"""员工加 token_version（小程序 token 的撤销靠它）

Revision ID: e4c5a3fe57a2
Revises: fa5686a9f878
Create Date: 2026-09-17 13:14:43.603163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4c5a3fe57a2'
down_revision = 'fa5686a9f878'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # staff 表里已经有账号了，所以必须给个 server_default——不然 Alembic 不知道
    # 老行该填什么，ALTER 会直接失败（这个坑 README 的「新模块的固定流程」里记着）
    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.add_column(sa.Column('token_version', sa.Integer(), nullable=False,
                                      server_default='0'))
        # 填完老数据就把默认值撤掉：留着的话，将来谁插一行忘了给值会被数据库
        # 悄悄填 0，而应用层根本不知道这件事发生过
        batch_op.alter_column('token_version', server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.drop_column('token_version')

    # ### end Alembic commands ###
