"""订单加积分抵扣字段

Revision ID: f4928cf14b52
Revises: 2d651d48f58d
Create Date: 2026-09-16 19:18:26.772753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4928cf14b52'
down_revision = '2d651d48f58d'
branch_labels = None
depends_on = None


def upgrade():
    # 表里已经有数据了，NOT NULL 的新列必须给 server_default，否则迁移直接失败。
    # 老订单都没用过积分抵扣，补 0。
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('points_used', sa.Integer(), nullable=False,
                                      server_default='0'))
        batch_op.add_column(sa.Column('points_discount', sa.Numeric(precision=10, scale=2),
                                      nullable=False, server_default='0'))
        # 填完老数据就把默认值撤掉，免得数据库里留一个和模型重复的隐式默认
        batch_op.alter_column('points_used', server_default=None)
        batch_op.alter_column('points_discount', server_default=None)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('points_discount')
        batch_op.drop_column('points_used')

    # ### end Alembic commands ###
