"""老系统共存：ID 映射、同步记录、对账记录

Revision ID: fa5686a9f878
Revises: 9b07332e7800
Create Date: 2026-09-16 23:05:08.508760

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'fa5686a9f878'
down_revision = '9b07332e7800'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('legacy_map',
    sa.Column('target_type', sa.String(length=20), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('legacy_id', sa.String(length=64), nullable=False),
    sa.Column('remark', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('target_type', 'legacy_id', name='uq_legacy_map_legacy_id'),
    sa.UniqueConstraint('target_type', 'target_id', name='uq_legacy_map_target_id')
    )
    with op.batch_alter_table('legacy_map', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_legacy_map_legacy_id'), ['legacy_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_legacy_map_target_id'), ['target_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_legacy_map_target_type'), ['target_type'], unique=False)

    op.create_table('sync_record',
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('target', sa.String(length=32), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('ref', sa.String(length=128), nullable=False),
    sa.Column('message', sa.String(length=255), nullable=False),
    sa.Column('synced_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sync_record', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sync_record_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_sync_record_direction'), ['direction'], unique=False)
        batch_op.create_index(batch_op.f('ix_sync_record_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_sync_record_target'), ['target'], unique=False)

    op.create_table('reconciliation',
    sa.Column('biz_date', sa.Date(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('expected_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('actual_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('diff_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('mismatch_count', sa.Integer(), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.Column('checked_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    # 外键必须**显式起名**：交给 MySQL 起就是 `reconciliation_ibfk_1`，
    # 名字带序号，换个环境顺序一变就对不上（见 52bd067fde97 里那段说明）。
    # 项目惯例是 `fk_<表>_<列>`
    sa.ForeignKeyConstraint(['store_id'], ['store.id'],
                            name='fk_reconciliation_store_id', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reconciliation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reconciliation_biz_date'), ['biz_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_reconciliation_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_reconciliation_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_reconciliation_store_id'), ['store_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # **不用自动生成的 drop_index 那几行**：`reconciliation.store_id` 上的索引
    # 被外键用着，MySQL 不让单独删（errno 1553 Cannot drop index ... needed in a
    # foreign key constraint）。索引和表一起删就行——`DROP TABLE` 会带走它的索引
    op.drop_table('reconciliation')
    op.drop_table('sync_record')
    op.drop_table('legacy_map')
